Use relative path when on CI (#11)
* fix: use relative path when on CI

* feat: include super dataset generator

* fix: try non-parallel in CI; update super-dataset code

* fix: release limit on super dataset

* fix: try non-parallel in CI

* fix: setup environment

* fix: try relaxing to see CI complaint

* fix: force inclusion of config file

* fix: debug config path and add limit

* fix: ci

* fix: change name of environment variable

* fix: fix workflow

* fix: fix workflow

* feat: re-enable parallel

* feat: re-enable parallel

* feat: re-disable parallel

* feat: re-ensable parallel, set dataset limit, increase CRON

* feat: use smarter counter setup

* feat: use smarter counter setup

* feat: use smarter counter setup

* feat: use the right workflow

* feat: use smarter counter setup

diff --git a/.github/workflows/update-bids-dandisets.yml b/.github/workflows/update-bids-dandisets.yml
--- a/.github/workflows/update-bids-dandisets.yml
+++ b/.github/workflows/update-bids-dandisets.yml
@@ -2,11 +2,15 @@ name: Update BIDS Dandisets
 
 on:
   schedule:
-    - cron: "0 12 * * *"  # noon EST
+    - cron: "0 */4 * * *"  # every 4 hours
   workflow_dispatch:
 
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
+
 env:
-  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  _GITHUB_API_KEY: ${{ secrets._GITHUB_API_KEY }}
 
 jobs:
   UpdateBidsDandisets:
@@ -23,15 +27,16 @@ jobs:
         run: pip install -e git+https://github.com/con/nwb2bids@main#egg=nwb2bids[dandi]
 
       - name: Run generation script
+#        run: python scripts/parallel_generate.py
         run: python scripts/generate.py
         env:
           SANITIZATION_LEVEL: 0
 
-      - name: Printout all errors from parallel logs
-        run: cat ./.parallel_logs/*.log || echo "No errors found in logs."
+#      - name: Printout all errors from parallel logs
+#        run: cat ./.parallel_logs/*.log || echo "No errors found in logs."
 
 #      - name: Run generation script with minimal sanitization
-#        run: python scripts/generate.py
+#        run: python scripts/parallel_generate.py
 #        env:
 #          SANITIZATION_LEVEL: 1
 
